### PR TITLE
Timeline Component English Translation

### PR DESCRIPTION
**Pull request by BigChief45**
This is my take on trying to translate the [Timeline component's documentation](https://www.iviewui.com/components/timeline#).

I still have a few doubts regarding the following:

- Difference between 問世 and 發佈.
- Using "ghost node" (幽灵节点) to describe the last node when `pending` property is used.

Would appreciate some feedback, and please let me know if anything is missing.

Thanks!

### CODE REVIEW

**Comment by lcx960324** [comment]
The demo of the component are related to the code at the right. So don't need to translate the content inside the component demo. XD

**Comment by icarusion** [comment]
We plan to unify to replace the sample code section after translate all pages.

**Comment by icarusion** [comment]
@BigChief45 `ghost node` is good. iView's style is powered by AntDesign, maybe we can reference it. https://ant.design/components/timeline/

**Comment by BigChief45** [comment]
So the content inside `<div slot="demo">` should all be in Chinese?

```html
<div slot="demo">
                    <Timeline>
                        <Timeline-item>
                            <p class="time">1976</p>
                            <p class="content">Apple I is released</p>
                        </Timeline-item>
                        <Timeline-item>
                            <p class="time">1984</p>
                            <p class="content">Macintosh is released</p>
                        </Timeline-item>
                        <Timeline-item>
                            <p class="time">2007</p>
                            <p class="content">iPhone is released</p>
                        </Timeline-item>
                        <Timeline-item>
                            <p class="time">2010</p>
                            <p class="content">iPad is released</p>
                        </Timeline-item>
                        <Timeline-item>
                            <p class="time">10/05/2011</p>
                            <p class="content">Steve Jobs passes away</p>
                        </Timeline-item>
                    </Timeline>
                </div>
```

What about `<Demo title="">`?

**Comment by lcx960324** [comment]
That's right. <Demo title=""> needs to be translated. Thx a lot. XD

**Comment by BigChief45** [comment]
Changes made.

**Pull request merged**
